# Generated by Django 5.1.7 on 2025-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Regno',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
