# Generated by Django 5.1.7 on 2025-05-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_id_alter_student_regno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departmnet',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Regno',
            new_name='regno',
        ),
    ]
