# Generated by Django 5.1.7 on 2025-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_departmnet_student_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="regno",
            field=models.CharField(max_length=100),
        ),
    ]
