# Generated by Django 5.1.7 on 2025-05-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_id_alter_student_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2004-05-21'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(default='21BCA201', max_length=8),
        ),
    ]
