# Generated by Django 5.1.7 on 2025-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='city',
        ),
    ]
