# Generated by Django 5.2.1 on 2025-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_address_student_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(default='21BCA201', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
