# Generated by Django 5.2.1 on 2025-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_student_id_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(default='21BCA201', max_length=8, primary_key=True, serialize=False),
        ),
    ]
